### ISSUE TITLE
Level placeholder for visited island not working in latest version

### ISSUE THREAD

**Issue by PhanaticD** [BentoBoxWorld/Level#106]
#### Describe the bug

Level placeholder is giving a nullpointer

https://pastebin.com/raw/jEZQeYBQ

#### Steps to reproduce the behavior

use the placeholder, in my situation it is with featherboard
##### BentoBox Version (Mandatory)

```
[16:06:13 INFO]: Running Invalid 1.14.4.
[16:06:13 INFO]: BentoBox version: 1.9.0-SNAPSHOT-b1497
[16:06:13 INFO]: Database: MARIADB
[16:06:13 INFO]: Loaded Game Worlds:
[16:06:13 INFO]: skyblock (SkyBlock): Overworld, Nether, End
[16:06:13 INFO]: Loaded Addons:
[16:06:13 INFO]: Biomes 1.6.0.1-SNAPSHOT-b149 (ENABLED)
[16:06:13 INFO]: BSkyBlock 1.9.0 (ENABLED)
[16:06:13 INFO]: Challenges 0.9.0-SNAPSHOT-#394 (ENABLED)
[16:06:13 INFO]: ControlPanel 1.7.0 (ENABLED)
[16:06:13 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[16:06:13 INFO]: Greenhouses 0.4.5-SNAPSHOT (ENABLED)
[16:06:13 INFO]: IslandFly 1.7.2-SNAPSHOT (ENABLED)
[16:06:13 INFO]: Level 1.9.0-SNAPSHOT-LOCAL (ENABLED)
[16:06:13 INFO]: MagicCobblestoneGenerator 1.7.1-SNAPSHOT-#86 (ENABLED)
[16:06:13 INFO]: TwerkingForTrees 1.0.1 (ENABLED)
```

#### Plugins (Optional)

```
can be provided privately if needed
```
 
### Additional context (Optional)

```
[15:58:26] [Craft Scheduler Thread - 26/ERROR]: [FeatherBoard] Error in placeholder: {placeholderapi_level_bskyblock_visited_island_level}
[15:58:26] [Craft Scheduler Thread - 26/ERROR]: [FeatherBoard] java.lang.NullPointerException
        at world.bentobox.level.Level.getLevelsData(Level.java:79)
        at world.bentobox.level.Level.getIslandLevel(Level.java:68)
        at world.bentobox.level.Level.lambda$null$4(Level.java:166)
        at java.util.Optional.map(Optional.java:215)
        at world.bentobox.level.Level.lambda$null$6(Level.java:166)
        at world.bentobox.bentobox.api.placeholders.placeholderapi.BasicPlaceholderExpansion.onPlaceholderRequest(BasicPlaceholderExpansion.java:47)
        at world.bentobox.bentobox.api.placeholders.placeholderapi.AddonPlaceholderExpansion.onPlaceholderRequest(AddonPlaceholderExpansion.java:5)
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234)
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:375)
        at be.maximvdw.placeholdercore.placeholders.PlaceholderAPIPlaceholderPack$1.getResult(PlaceholderAPIPlaceholderPack.java:37)
        at be.maximvdw.placeholdercore.placeholders.PlaceholderAPIPlaceholderPack$1.getResult(PlaceholderAPIPlaceholderPack.java:26)
        at be.maximvdw.featherboard.dD.a(dD.java:260)
        at be.maximvdw.featherboard.dM.a(dM.java:35)
        at be.maximvdw.featherboard.Q.a(Q.java:66)
        at be.maximvdw.featherboard.Q.a(Q.java:76)
        at be.maximvdw.featherboard.api.scoreboard.ScoreboardLine.updatePlaceholders(ScoreboardLine.java:63)
        at be.maximvdw.featherboard.api.scoreboard.ScoreboardGroup$AnimationUpdater.run(ScoreboardGroup.java:7)
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by tastybento** [comment]
Should be fixed with latest 1.9.1 build.
