### ISSUE TITLE
/is level does not work with latest bentobox SNAPSHOT version

### ISSUE THREAD

**Issue by Tina-King** [BentoBoxWorld/Level#117]
#### Describe the bug

/is level does not work with the latest bentobox version.

#### Steps to reproduce the behavior

Type /is level

#### Expected behavior

It should return the island level

##### BentoBox Version (Mandatory)

```
bbox v
[20:37:47 INFO]: Running PAPER 1.15.1.
[20:37:47 INFO]: BentoBox version: 1.11.0-SNAPSHOT-b1569
[20:37:47 INFO]: Database: JSON
[20:37:47 INFO]: Loaded Game Worlds:
[20:37:47 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
[20:37:47 INFO]: Loaded Addons:
[20:37:47 INFO]: Biomes 1.6.0.1 (ENABLED)
[20:37:47 INFO]: Border 1.0.3 (ENABLED)
[20:37:47 INFO]: BSkyBlock 1.10.1-SNAPSHOT-b583 (ENABLED)
[20:37:47 INFO]: Challenges 0.9.0-SNAPSHOT-#395 (ENABLED)
[20:37:47 INFO]: Chat 1.0.2-SNAPSHOT-b11 (ENABLED)
[20:37:47 INFO]: ControlPanel 1.7.0 (ENABLED)
[20:37:47 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[20:37:47 INFO]: ExtraMobs 1.10.0.1-SNAPSHOT-b0 (ENABLED)
[20:37:47 INFO]: Greenhouses 1.0.0 (ENABLED)
[20:37:47 INFO]: IslandFly 1.7.2-SNAPSHOT-b101 (ENABLED)
[20:37:47 INFO]: Level 1.9.1-SNAPSHOT-b332 (ENABLED)
[20:37:47 INFO]: Limits 1.9.1-SNAPSHOT-b194 (ENABLED)
[20:37:47 INFO]: Warps 1.9.2-SNAPSHOT-b218 (ENABLED)
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

Console Error:
```
[20:39:38 INFO]: MissLou issued server command: /is level
[20:39:41 WARN]: [BentoBox] Task #17142 for BentoBox v1.11.0-SNAPSHOT-b1569 generated an exception
java.lang.IncompatibleClassChangeError: Expecting non-static method world.bentobox.bentobox.api.events.addon.AddonEvent.builder()Lworld/bentobox/bentobox/api/events/addon/AddonEvent$AddonEventBuilder;
at world.bentobox.level.calculators.PlayerLevel.fireIslandLevelCalcEvent(PlayerLevel.java:69) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-41]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-41]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[20:39:44 WARN]: [BentoBox] Task #17469 for BentoBox v1.11.0-SNAPSHOT-b1569 generated an exception
java.lang.IncompatibleClassChangeError: Expecting non-static method world.bentobox.bentobox.api.events.addon.AddonEvent.builder()Lworld/bentobox/bentobox/api/events/addon/AddonEvent$AddonEventBuilder;
at world.bentobox.level.calculators.PlayerLevel.fireIslandLevelCalcEvent(PlayerLevel.java:69) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-41]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-41]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-41]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by andris155** [comment]
Same problem

**Comment by tastybento** [comment]
Latest snapshot should fix this.

**Comment by Tina-King** [comment]
This issue has returned on build on `Level-1.9.3-SNAPSHOT-b337.jar`

Error:
```
[09:58:04 WARN]: [BentoBox] Task #5276 for BentoBox v1.11.0-SNAPSHOT-b1569 generated an exception
java.lang.IncompatibleClassChangeError: Expecting non-static method world.bentobox.bentobox.api.events.addon.AddonEvent.builder()Lworld/bentobox/bentobox/api/events/addon/AddonEvent$AddonEventBuilder;
	at world.bentobox.level.calculators.PlayerLevel.fireIslandLevelCalcEvent(PlayerLevel.java:69) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-29]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
```
bbox v
[10:08:16 INFO]: Running PAPER 1.15.1.
[10:08:16 INFO]: BentoBox version: 1.11.0-SNAPSHOT-b1569
[10:08:16 INFO]: Database: MYSQL
[10:08:16 INFO]: Loaded Game Worlds:
[10:08:16 INFO]: skyblock_world (SkyBlock): Overworld, Nether, End
[10:08:16 INFO]: Loaded Addons:
[10:08:16 INFO]: Biomes 1.6.0.1-SNAPSHOT-b150 (ENABLED)
[10:08:16 INFO]: Border 1.0.3 (ENABLED)
[10:08:16 INFO]: BSkyBlock 1.10.1-SNAPSHOT-b583 (ENABLED)
[10:08:16 INFO]: Challenges 0.9.0-SNAPSHOT-b396 (ENABLED)
[10:08:16 INFO]: Chat 1.0.2-SNAPSHOT-b12 (ENABLED)
[10:08:16 INFO]: ExtraMobs 1.10.0.1-SNAPSHOT-b0 (ENABLED)
[10:08:16 INFO]: Level 1.9.3-SNAPSHOT-b337 (ENABLED)
[10:08:16 INFO]: Limits 1.9.1-SNAPSHOT-b198 (ENABLED)
[10:08:16 INFO]: Warps 1.9.2-SNAPSHOT-b219 (ENABLED)
```

**Comment by Tina-King** [comment]
@tastybento

**Comment by tastybento** [comment]
Please upgrade to the latest BentoBox snapshot. You are on the latest Level, but it must be matched with the associated BentoBox version (Build 1587 fixed it).
