### ISSUE TITLE
Level calculation not working properly on 1.15.1

### ISSUE THREAD

**Issue by N0tMyFaultOG** [BentoBoxWorld/Level#120]
#### Describe the bug

/is level doesn't seem to work. Running the command fires the following stacktrace: 
```
[16:05:13 INFO]: NotMyFault issued server command: /is level
[16:05:14 WARN]: [BentoBox] Task #2336 for BentoBox v1.11.0-SNAPSHOT-b1570 generated an exception
java.lang.IncompatibleClassChangeError: Expecting non-static method world.bentobox.bentobox.api.events.addon.AddonEvent.builder()Lworld/bentobox/bentobox/api/events/addon/AddonEvent$AddonEventBuilder;
        at world.bentobox.level.calculators.PlayerLevel.fireIslandLevelCalcEvent(PlayerLevel.java:69) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-45]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-45]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-45]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-45]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-45]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-45]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

#### Steps to reproduce the behavior

Download BBox, Levels and run /is level

#### Expected behavior

Calculating the levers rather than firing a stacktrace.

#### Screenshots and videos (Optional)

/

##### BentoBox Version (Mandatory)

```
[16:06:49 INFO]: Running PAPER 1.15.1.
[16:06:49 INFO]: BentoBox version: 1.11.0-SNAPSHOT-b1570
[16:06:49 INFO]: Database: JSON
[16:06:49 INFO]: Loaded Game Worlds:
[16:06:49 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
[16:06:49 INFO]: Loaded Addons:
[16:06:49 INFO]: Biomes 1.6.0.1-SNAPSHOT-b150 (ENABLED)
[16:06:49 INFO]: BSkyBlock 1.10.1-SNAPSHOT-b585 (ENABLED)
[16:06:49 INFO]: Challenges 0.9.0-SNAPSHOT-b396 (ENABLED)
[16:06:49 INFO]: Level 1.9.3-SNAPSHOT-b337 (ENABLED)
[16:06:49 INFO]: MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b93 (ENABLED)
[16:06:49 INFO]: Warps 1.9.2-SNAPSHOT-b219 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
BentoBox API was broken. You'll need to use the latest BentoBox build to fix this error. 227ebef82431b7dbd312c114f352abcadf36812b
