### ISSUE TITLE
Level failure

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/Level#147]
##### BentoBox Version (Mandatory)

```
>bbox version
[16:06:22] [Server thread/INFO]: Running SPIGOT 1.15.2.
[16:06:22] [Server thread/INFO]: BentoBox version: 1.13.0-SNAPSHOT-b1731
[16:06:22] [Server thread/INFO]: Database: JSON
[16:06:22] [Server thread/INFO]: Loaded Game Worlds:
[16:06:22] [Server thread/INFO]: world_skyblock (SkyBlock): Overworld, [nether_color]Nether, [end_color]End
[16:06:22] [Server thread/INFO]: Loaded Addons:
[16:06:22] [Server thread/INFO]: Biomes 1.12.0-SNAPSHOT-b159 (ENABLED)
[16:06:22] [Server thread/INFO]: BSkyBlock 1.13.0-SNAPSHOT-b601 (ENABLED)
[16:06:22] [Server thread/INFO]: Challenges 0.9.0-SNAPSHOT-b404 (ENABLED)
[16:06:22] [Server thread/INFO]: ExtraMobs 1.11.0.2-SNAPSHOT-b4 (ENABLED)
[16:06:22] [Server thread/INFO]: Level 2.0.0-SNAPSHOT-b349 (ERROR)
```

#### Describe the bug

On server start:
```
[15:57:02] [Server thread/WARN]: [BentoBox] [Level] Converting old config.yml format - shifting blocks, limits and worlds to blockconfig.yml
[15:57:02] [Server thread/ERROR]: [BentoBox] [Level] blockconfig.yml already exists! Saving config as blockconfig.yml.2
[15:57:02] [Server thread/ERROR]: [BentoBox] Skipping Level due to an unhandled exception...
[15:57:02] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException
        at world.bentobox.level.Level.copyConfigSection(Level.java:188)
        at world.bentobox.level.Level.loadSettings(Level.java:176)
        at world.bentobox.level.Level.onLoad(Level.java:149)
        at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:134)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:78)
        at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
blockconfig.yml.2 was not created.

If I remove blockconfig.yml and re-start:
```
[16:03:36] [Server thread/WARN]: [BentoBox] [Level] Converting old config.yml format - shifting blocks, limits and worlds to blockconfig.yml
[16:03:36] [Server thread/ERROR]: [BentoBox] Skipping Level due to an unhandled exception...
[16:03:36] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException
        at world.bentobox.level.Level.copyConfigSection(Level.java:188)
        at world.bentobox.level.Level.loadSettings(Level.java:176)
        at world.bentobox.level.Level.onLoad(Level.java:149)
        at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:134)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:78)
        at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:164)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tastybento** [comment]
Thanks. Fixed by 0a4b0af93136a32b8c505264b82e592eecd6003b
