### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by arts7493** [BentoBoxWorld/Level#169]
#### Describe the bug
```
[19:07:59] [Server thread/INFO]: [BentoBox] DEBUG: TeamJoinedEvent
[19:07:59] [Server thread/ERROR]: Could not pass event TeamJoinedEvent to BentoBox v1.14.0
java.lang.NullPointerException: null
	at world.bentobox.level.objects.LevelsData.remove(LevelsData.java:169) ~[?:?]
	at world.bentobox.level.LevelsManager.removeEntry(LevelsManager.java:401) ~[?:?]
	at world.bentobox.level.listeners.IslandActivitiesListeners.remove(IslandActivitiesListeners.java:73) ~[?:?]
	at world.bentobox.level.listeners.IslandActivitiesListeners.onIsland(IslandActivitiesListeners.java:88) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1008.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-378]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-378]
	at world.bentobox.bentobox.api.events.team.TeamEvent$TeamEventBuilder.build(TeamEvent.java:216) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.acceptTeamInvite(IslandTeamInviteAcceptCommand.java:175) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.lambda$execute$2(IslandTeamInviteAcceptCommand.java:89) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[19:08:00] [Server thread/INFO]: MIN_KyoungHun issued server command: /island team accept
[19:08:00] [Server thread/INFO]: MIN_KyoungHun [7f513df5-a772-4cef-a685-ef4828752b3e]: /island team accept
[19:08:00] [Server thread/INFO]: [BentoBox] DEBUG: TeamJoinedEvent
[19:08:00] [Server thread/ERROR]: Could not pass event TeamJoinedEvent to BentoBox v1.14.0
java.lang.NullPointerException: null
	at world.bentobox.level.objects.LevelsData.remove(LevelsData.java:169) ~[?:?]
	at world.bentobox.level.LevelsManager.removeEntry(LevelsManager.java:401) ~[?:?]
	at world.bentobox.level.listeners.IslandActivitiesListeners.remove(IslandActivitiesListeners.java:73) ~[?:?]
	at world.bentobox.level.listeners.IslandActivitiesListeners.onIsland(IslandActivitiesListeners.java:88) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1008.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-378]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-378]
	at world.bentobox.bentobox.api.events.team.TeamEvent$TeamEventBuilder.build(TeamEvent.java:216) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.acceptTeamInvite(IslandTeamInviteAcceptCommand.java:175) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamInviteAcceptCommand.lambda$execute$2(IslandTeamInviteAcceptCommand.java:89) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

```
[19:14:50] [Server thread/INFO]: Arts_ issued server command: /is team leave
[19:14:50] [Server thread/INFO]: [BentoBox] DEBUG: TeamLeaveEvent
[19:14:50] [Server thread/ERROR]: Could not pass event TeamLeaveEvent to BentoBox v1.14.0
java.lang.NullPointerException: null
	at world.bentobox.level.objects.LevelsData.remove(LevelsData.java:169) ~[?:?]
	at world.bentobox.level.LevelsManager.removeEntry(LevelsManager.java:401) ~[?:?]
	at world.bentobox.level.listeners.IslandActivitiesListeners.remove(IslandActivitiesListeners.java:73) ~[?:?]
	at world.bentobox.level.listeners.IslandActivitiesListeners.onIsland(IslandActivitiesListeners.java:109) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1006.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-378]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-378]
	at world.bentobox.bentobox.api.events.team.TeamEvent$TeamEventBuilder.build(TeamEvent.java:216) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamLeaveCommand.leave(IslandTeamLeaveCommand.java:119) ~[?:?]
	at world.bentobox.bentobox.api.commands.island.team.IslandTeamLeaveCommand.lambda$execute$0(IslandTeamLeaveCommand.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

#### Steps to reproduce the behavior
accept invite and team leave

##### Output of `/bbox version` (Mandatory)

```
[19:11:35] [Server thread/INFO]: Running PAPER 1.15.2.
[19:11:35] [Server thread/INFO]: BentoBox version: 1.14.0
[19:11:35] [Server thread/INFO]: Database: JSON
[19:11:35] [Server thread/INFO]: Loaded Game Worlds:
[19:11:35] [Server thread/INFO]: bskyblock_world (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
[19:11:35] [Server thread/INFO]: Loaded Addons:
[19:11:35] [Server thread/INFO]: Biomes 1.7.0 (ENABLED)
[19:11:35] [Server thread/INFO]: BSkyBlock 1.14.0 (ENABLED)
[19:11:35] [Server thread/INFO]: Level 2.3.0 (ENABLED)
[19:11:35] [Server thread/INFO]: Limits 1.14.0 (ENABLED)
[19:11:35] [Server thread/INFO]: Warps 1.10.0 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
@arts7493 Please try latest build.

This is caused when upgrading and the new data that is stored is not there in the old records.
