### ISSUE TITLE
Multiple errors on Level upgrade

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/Level#210]
#### Describe the bug

Multiple ERRORs on start-up, and Level disabled.

#### Steps to reproduce the behavior

- Update to Level-2.5.1-b434
- Start server
- Read errors in log

#### Expected behavior
Clean start-up

#### Screenshots and videos (Optional)

```
[18:35:12] [Server thread/ERROR]: [BentoBox] Could not load config object! Method not found: setLogReportToConsole
[18:35:12] [Server thread/ERROR]: [BentoBox] java.beans.IntrospectionException: Method not found: setLogReportToConsole
        at java.desktop/java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:114)
        at java.desktop/java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:74)
        at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.createObject(YamlDatabaseHandler.java:162)
        at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.loadObject(YamlDatabaseHandler.java:95)
        at world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:64)
        at world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:81)
        at world.bentobox.level.Level.loadSettings(Level.java:67)
        at world.bentobox.level.Level.onLoad(Level.java:56)
        at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:87)
        at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:166)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:186)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
        at java.base/java.lang.Thread.run(Thread.java:834)
[18:35:12] [Server thread/ERROR]: [BentoBox] [Level] Level settings could not load! Addon disabled.
...
[18:36:34] [Server thread/ERROR]: [BentoBox] Skipping Level due to an unhandled exception...
[18:36:34] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException
        at world.bentobox.level.Level.lambda$onEnable$0(Level.java:84)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at world.bentobox.level.Level.onEnable(Level.java:85)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:234)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:179)
        at world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:186)
        at world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:172)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060)
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

##### Output of `/bbox version` (Mandatory)

```
>bbox ver
[18:42:39] [Server thread/INFO]: Running Invalid () 1.16.5.
[18:42:39] [Server thread/INFO]: BentoBox version: 1.16.0-SNAPSHOT-b1965
[18:42:39] [Server thread/INFO]: Database: JSON
[18:42:39] [Server thread/INFO]: Loaded Game Worlds:
[18:42:39] [Server thread/INFO]: world_skyblock (SkyBlock): Overworld, [nether_color]Nether, [end_color]End
[18:42:39] [Server thread/INFO]: Loaded Addons:
[18:42:39] [Server thread/INFO]: Biomes 1.14.1-SNAPSHOT-b200 (ENABLED)
[18:42:39] [Server thread/INFO]: BSkyBlock 1.14.3 (ENABLED)
[18:42:39] [Server thread/INFO]: Challenges 0.8.4-SNAPSHOT-b438 (ENABLED)
[18:42:39] [Server thread/INFO]: ExtraMobs 1.11.0.4-SNAPSHOT-b7 (ENABLED)
[18:42:39] [Server thread/INFO]: Level 2.5.1-SNAPSHOT-b434 (ERROR)
```

**Comment by tastybento** [comment]
Fixed by https://github.com/BentoBoxWorld/Level/pull/209

**Comment by SlimeDog** [comment]
Thanks. Confirmed fixed in dev b435.
