### ISSUE TITLE
Events are broken with BentoBox 1.18

### ISSUE THREAD

**Issue by johnfriedrich** [BentoBoxWorld/Level#237]
### Expected behavior

is level works.

### Observed/Actual behavior

```[17:23:16] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.18.0-SNAPSHOT-b2165
org.bukkit.command.CommandException: Unhandled exception executing 'island level' in world.bentobox.bskyblock.BSkyBlock$1(island)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-279]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-279]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:647) ~[patched_1.17.1.jar:git-Paper-279]
	at world.bentobox.bentobox.api.user.User.performCommand(User.java:575) ~[BentoBox-1.18.0-SNAPSHOT-b2165.jar:?]
	at world.bentobox.controlpanel.panels.ControlPanelGenerator.lambda$generateButton$2(ControlPanelGenerator.java:142) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[BentoBox-1.18.0-SNAPSHOT-b2165.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[BentoBox-1.18.0-SNAPSHOT-b2165.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor872.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-279]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-279]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-279]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2802) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-279]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class world.bentobox.level.events.IslandPreLevelEvent does not define or inherit an implementation of the resolved method 'abstract org.bukkit.event.HandlerList getHandlers()' of abstract class org.bukkit.event.Event.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[patched_1.17.1.jar:git-Paper-279]
	at world.bentobox.level.LevelsManager.calculateLevel(LevelsManager.java:164) ~[Level-2.8.0-SNAPSHOT-b475.jar:?]
	at world.bentobox.level.commands.IslandLevelCommand.scanIsland(IslandLevelCommand.java:90) ~[Level-2.8.0-SNAPSHOT-b475.jar:?]
	at world.bentobox.level.commands.IslandLevelCommand.execute(IslandLevelCommand.java:70) ~[Level-2.8.0-SNAPSHOT-b475.jar:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[BentoBox-1.18.0-SNAPSHOT-b2165.jar:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[BentoBox-1.18.0-SNAPSHOT-b2165.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-279]
	... 29 more```

### Steps/models to reproduce

type is level

### BentoBox version

BentoBox v1.18.0-SNAPSHOT-b2165

### Plugin list

Level (2.8.0-SNAPSHOT-b475)

### Other

1.17.1.jar:git-Paper-279

**Comment by tastybento** [comment]
Should be fixed with latest commit.
