### ISSUE TITLE
Exception on island top at console

### ISSUE THREAD

**Issue by SlimeDog** [BentoBoxWorld/Level#24]
**Description**
> **island top**

at console generates the following error. In-game **/island top** opens the GUI.

**Steps to reproduce the behavior:**
```
>island top
[13:31:01 WARN]: Unexpected exception while parsing console command "island top"
org.bukkit.command.CommandException: Unhandled exception executing 'island top' in world.bentobox.bskyblock.commands.IslandCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687) [spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459) [spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.api.panels.Panel.open(Panel.java:94) ~[?:?]
        at world.bentobox.bentobox.api.panels.Panel.<init>(Panel.java:59) ~[?:?]
        at world.bentobox.bentobox.api.panels.builders.PanelBuilder.build(PanelBuilder.java:95) ~[?:?]
        at world.bentobox.level.TopTen.getGUI(TopTen.java:102) ~[?:?]
        at world.bentobox.level.commands.IslandTop.execute(IslandTop.java:20) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:237) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar-2018-11-10-0712:git-Spigot-947a8e7-3a91182]
        ... 7 more
```
**Expected behavior**
Command should be executable from the console, but obviously cannot open the GUI. A simple list of top islands would be nice.

Note that ASkyBlock on Spigot 1.12.2 produces:
> This command must be used in-game.

**Server Information:**
- Spigot 1.13.2 latest
- BentoBox version: 0.14.1
```
[13:34:59 INFO]: Bentobox version: 0.14.1
[13:34:59 INFO]: Loaded Game Worlds:
[13:34:59 INFO]: world_skyblock (BSkyBlock)
[13:34:59 INFO]: Loaded Add-Ons
[13:34:59 INFO]: BSkyBlock 0.5.0-SNAPSHOT
[13:34:59 INFO]: BentoBox-Challenges 0.0.3-SNAPSHOT
[13:34:59 INFO]: Level 0.1.0-SNAPSHOT
```

**Comment by Poslovitch** [comment]
That will be fixed in the next release (0.2.0). Thanks for the report :)
