### ISSUE TITLE
NoSuchMethodError when trying to remove stats

### ISSUE THREAD

**Issue by PapiCapi** [BentoBoxWorld/Level#316]
### Expected behavior

Being able to remove player's stats using the command `/bsbadmin stats remove [user]` .

### Observed/Actual behavior

The command does not dispatch and an error is thrown : 

```
[21:06:18] [Server thread/INFO]: Clad003 issued server command: /bsbadmin stats remove Lolorlie
[21:06:18] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bsbadmin stats remove Lolorlie' in world.bentobox.bskyblock.BSkyBlock$2(bsbadmin)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-451]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-451]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-451]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Set world.bentobox.bentobox.managers.IslandsManager.getIslands(org.bukkit.World, java.util.UUID)'
	at world.bentobox.level.commands.AdminTopRemoveCommand.execute(AdminTopRemoveCommand.java:60) ~[Level-2.13.0.jar:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:292) ~[BentoBox-2.3.0.jar:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:260) ~[BentoBox-2.3.0.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 28 more
```

### Steps/models to reproduce

Try to remove stats of a player.

### BentoBox version

![image](https://github.com/BentoBoxWorld/Level/assets/49530141/b84d9b34-8caa-4222-9dcd-34d61be7690e)

### Plugin list

[21:17:27 INFO]: Server Plugins (80):
[21:17:27 INFO]: Paper Plugins:
[21:17:27 INFO]:  - SignedVelocity
[21:17:27 INFO]: Bukkit Plugins:
[21:17:27 INFO]:  - *AntiAFK, AntiDecoCombat, ArmorStandTools, Bank, BentoBox, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Warps
[21:17:27 INFO]:  BlockLocker, BlockVillagersEnteringBoats, ChatCore, ChatItem, ChatLinker, ChatPing, Citizens, CitizensText, Core, CoreProtect
[21:17:27 INFO]:  CrazyCrates, DeACoudre, DecentHolograms, DeluxeMenus, Donjon, EffectItems, EndPortalPatcher, Essentials, EssentialsChat, EssentialsSpawn
[21:17:27 INFO]:  EventDropper, FarmLimiter, FastAsyncWorldEdit, ForceIgnore, FreedomChat, GadgetsMenu, Grades, IllegalStack, InfoMessage, Insights
[21:17:27 INFO]:  InvPerWorld, KitsSkyblock, LoadForce, LobbyPlayerCounter, LogementSky, LuckPerms, MinewebBridge, *ModReq, MoncubeCore, MoncubeExtraFlags
[21:17:27 INFO]:  Multiverse-Core, *NaruseAPI, NoCollision, OnTime, OpenInv, *OpGuard, PlaceholderAPI, Plan, PlanningsEvents, PlugManX
[21:17:27 INFO]:  PreventEnderChestUseBug, ProtocolLib, RankSwitcher, RotationWrench, SchematicMover, *SecondThreadAPI, Shopkeepers, Skript, spark, TAB
[21:17:27 INFO]:  TokenManager, UltimateStacker, Vault, ViaBackwards, ViaVersion, VoidGen, VoteMoncube, WorldGuard, WorldGuardExtraFlags

**Comment by tastybento** [comment]
Please try the latest release of Level (and BentoBox, if possible).
