### ISSUE TITLE
bug with items in the level value menu

### ISSUE THREAD

**Issue by Vinrey123** [BentoBoxWorld/Level#332]
### Expected behavior

Error correction

### Observed/Actual behavior

when entering the values menu in the levels addon, when scrolling through the menu, an error is written about a non-existent block.  As I understand it, Bento Box says that there is no TORCHFLOWER_CROP and PITCHER_CROP block.

### Steps/models to reproduce

```
[15:27:07 ERROR]: Could not pass event InventoryClickEvent to BentoBox v2.5.3
java.lang.IllegalArgumentException: PITCHER_CROP isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Level-2.16.0-1726643308499.jar/lv.id.bonne.panelutils.PanelUtils.getMaterialItem(PanelUtils.java:337) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/lv.id.bonne.panelutils.PanelUtils.getMaterialItem(PanelUtils.java:195) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.createMaterialButton(ValuePanel.java:617) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.createMaterialButton(ValuePanel.java:595) ~[Level-2.16.0-1726643308499.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.makeAddonButton(TemplatedPanel.java:295) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.makeButton(TemplatedPanel.java:248) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.processItemData(TemplatedPanel.java:126) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.populateInventoryPanel(TemplatedPanel.java:81) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.generatePanel(TemplatedPanel.java:61) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.<init>(TemplatedPanel.java:52) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.builders.TemplatedPanelBuilder.build(TemplatedPanelBuilder.java:150) ~[BentoBox-2.5.3.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.build(ValuePanel.java:101) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.lambda$createNextButton$20(ValuePanel.java:462) ~[Level-2.16.0-1726643308499.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[BentoBox-2.5.3.jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[BentoBox-2.5.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1485.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-83-2aaf436]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3216) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

```
java.lang.IllegalArgumentException: TORCHFLOWER_CROP isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Level-2.16.0-1726643308499.jar/lv.id.bonne.panelutils.PanelUtils.getMaterialItem(PanelUtils.java:337) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/lv.id.bonne.panelutils.PanelUtils.getMaterialItem(PanelUtils.java:195) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.createMaterialButton(ValuePanel.java:617) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.createMaterialButton(ValuePanel.java:595) ~[Level-2.16.0-1726643308499.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.makeAddonButton(TemplatedPanel.java:295) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.makeButton(TemplatedPanel.java:248) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.processItemData(TemplatedPanel.java:126) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.populateInventoryPanel(TemplatedPanel.java:81) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.generatePanel(TemplatedPanel.java:61) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.TemplatedPanel.<init>(TemplatedPanel.java:52) ~[BentoBox-2.5.3.jar:?]
        at BentoBox-2.5.3.jar/world.bentobox.bentobox.api.panels.builders.TemplatedPanelBuilder.build(TemplatedPanelBuilder.java:150) ~[BentoBox-2.5.3.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.build(ValuePanel.java:101) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.panels.ValuePanel.lambda$createSearchButton$8(ValuePanel.java:261) ~[Level-2.16.0-1726643308499.jar:?]
        at Level-2.16.0-1726643308499.jar/world.bentobox.level.util.ConversationUtils$1.acceptInput(ConversationUtils.java:60) ~[Level-2.16.0-1726643308499.jar:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at org.bukkit.craftbukkit.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:2428) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at InteractiveChat-4.2.12.0.jar/com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$1(RedispatchSignedPacket.java:79) ~[InteractiveChat-4.2.12.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-83-2aaf436]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### BentoBox version

Plugin BentoBox - 2.5.3
Addon Level - 2.16.0
Minecraft version - 1.21.1

**Comment by tastybento** [comment]
Thanks. Fixed, and I'll do an updated release.
