### ISSUE TITLE
Placeholder level_bskyblock-island-level

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Level#86]
**Description**
The level placeholder seems to cause errors.
```
15.09.2019 - 17:12:23 - [TAB v2.5.2-pre15] PlaceholderAPI replace task failed.
15.09.2019 - 17:12:23 - [TAB v2.5.2-pre15] PlaceholderAPI version: 2.10.3
15.09.2019 - 17:12:23 - [TAB v2.5.2-pre15] String to parse:         &b%level_bskyblock-island-level%
15.09.2019 - 17:12:23 - [TAB v2.5.2-pre15] Please send this error to the FIRST author whose name or plugin name you see here:
15.09.2019 - 17:12:23 - java.lang.NullPointerException: null
15.09.2019 - 17:12:23 -        at world.bentobox.level.placeholders.LevelPlaceholder.onReplace(LevelPlaceholder.java:32)
15.09.2019 - 17:12:23 -        at world.bentobox.bentobox.api.placeholders.placeholderapi.BasicPlaceholderExpansion.onPlaceholderRequest(BasicPlaceholderExpansion.java:48)
15.09.2019 - 17:12:23 -        at world.bentobox.bentobox.api.placeholders.placeholderapi.AddonPlaceholderExpansion.onPlaceholderRequest(AddonPlaceholderExpansion.java:5)
15.09.2019 - 17:12:23 -        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:40)
15.09.2019 - 17:12:23 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234)
15.09.2019 - 17:12:23 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:374)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.shared.Placeholders.setPlaceholderAPIPlaceholders(Placeholders.java:77)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.shared.Property.isUpdateNeeded(Property.java:90)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.premium.Scoreboard$Score.replaceText(Scoreboard.java:104)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.premium.Scoreboard$Score.updatePrefixSuffix(Scoreboard.java:139)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.premium.Scoreboard.refresh(Scoreboard.java:86)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.premium.ScoreboardManager$1.run(ScoreboardManager.java:43)
15.09.2019 - 17:12:23 -        at me.neznamy.tab.shared.Shared$2.run(Shared.java:136)
15.09.2019 - 17:12:23 -        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15.09.2019 - 17:12:23 -        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15.09.2019 - 17:12:23 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15.09.2019 - 17:12:23 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15.09.2019 - 17:12:23 -        at java.lang.Thread.run(Thread.java:748)
```
The plugin TAB wants to read this placeholder.
Although everything seems to work just fine, this error appear to have something to cause this error.
**Steps to reproduce the behavior:**
1. Tab is using the placeholder
2. Player joins and placeholder must be presented
3. Error does not appear on the console but in a seperate error file of the Tab plugin

**Expected behavior**
Ideally, no error should be produced

**Screenshots**
Not applicable

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: [Linux]
 - Java Version: [OpenJdk 1.8.0]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed?
```
Running PAPER 1.14.4.
BentoBox version: 1.8.0-SNAPSHOT-b1381
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.2-SNAPSHOT-b141 (ENABLED)
BSkyBlock 1.8.0-SNAPSHOT-b457 (ENABLED)
Challenges 0.8.0 (ENABLED)
Level 1.7.0-SNAPSHOT-b284 (ENABLED)
Limits 1.7.0-SNAPSHOT-b167 (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
Warps 1.7.0 (ENABLED)
```
 - Other plugins? [BentoBox, ChestShop, dynmap*, LuckPerms, mcMMO, PlaceholderAPI*, PlugMan, TAB, Vault, WorldBorder, WorldEdit, WorldGuard]

**Additional context**
PlaceholderAPI 2.10.3

**Comment by tastybento** [comment]
Hmm, I can't replicate this right now. I added the placeholder to the config file and hit tab and I can see my level. I tried with an island and without. I don't get an error file. 
From the code, a null error would occur only if some parts of the code had not been initialized. Maybe this was due to a reload? I don't know, sorry.

**Comment by x1p** [comment]
It's pretty random, but I have it again today. It only happens when someone joins.
(Meanwhile, placeholderapi is updated in this error)
https://hastebin.com/lapurotozo.sql

**Comment by tastybento** [comment]
I think there's a placeholder request being made on a null player. I added some handling to BentoBox. Let's see if that fixes it.
