### ISSUE TITLE
Island level lost on unregistering and reregistering an island

### ISSUE THREAD

**Issue by Tina-King** [BentoBoxWorld/Level#90]
**Description**
When I unregister from my island (bsbadmin unregister) and to create another island and then and then reregister to the island (bsbadmin register) the island level came out at around negative 30,000.

**Steps to reproduce the behavior:**
1. Deregister from your island (noting your current island level)
2. Create a new island and then deregister from it (This part is important)
3. Reregister to your island and you will find the level is messed up.

**Expected behavior**
The island level should be retained.

**Comment by tastybento** [comment]
Yes, there's an issue with zeroing the island level when you use the admin register/unregister commands.

For my reference:

```
java.lang.NullPointerException: null
	at world.bentobox.bentobox.managers.PlayersManager.getDeaths(PlayersManager.java:371) ~[?:?]
	at world.bentobox.level.listeners.IslandTeamListeners.zeroLevel(IslandTeamListeners.java:104) ~[?:?]
	at world.bentobox.level.listeners.IslandTeamListeners.lambda$onNewIsland$0(IslandTeamListeners.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-192]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-192]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by tastybento** [comment]
To fix this will require a reworking of how Level manages levels. Currently, it stores the level handicap in the user's data store so using the admin command to unregister and register does result in weird values. It'll take a bit of time to redo this.
